### ISSUE TITLE
CursorIM doesn't work fine.

### ISSUE THREAD

**Issue by azarashichop** [aereal/vim-colors-japanesque#4]
gvimrcに記載しても、カラースキームファイルに直接指定しても動作しません。
※gvimrc上でカラースキームを他のものに変えると正常に動作する。

よろしくお願いします。

**Comment by foooomio** [comment]
https://github.com/aereal/vim-colors-japanesque/blob/master/colors/japanesque.vim#L65

`gui=reverse` が指定されているのが問題のようです。
`highlight Cursor gui=NONE` で解決できるかと思います。

**Comment by foooomio** [comment]
`highlight Cursor gui=reverse` が指定されているので、`CursorIM` には `guifg` に色を指定してみてください。

**Comment by azarashichop** [comment]
ご連絡遅くなり申し訳ありません。

動作確認して、結果をフィードバックします。

**Comment by azarashichop** [comment]
ご指摘の通りに設定をためし、正常に動作することが確認できました。
御対応ありがとうございます！！

**Comment by foooomio** [comment]
いえいえ、通りすがりのものですので。お役に立てて幸いです。
解決されましたら、Issueをクローズされると良いかと思います。

**Comment by azarashichop** [comment]
はい、では本件はこれでクローズとさせていただきます。
ありがとうございました。
