### ISSUE TITLE
Error with vim/neovim in iTerm2

### ISSUE THREAD

**Issue by tostr7191** [aereal/vim-colors-japanesque#5]
Hi

After installing your colorscheme I get the following error on vim startup:

```
Error detected while processing function <SNR>39_set_highlight_colors[27]..<SNR>39_add_to_highlight_group:
line    1:
E421: Color name or number not recognized: ctermfg=-1
```

Also relevant maybe (running in tmux):

```
[~]$ echo $TERM
screen-256color
```

Any ideas why this could be happening? vim/neovim behave the same way. Also the theme does not look right if I just ignore the error (red/pinkish colors are not displayed).

Thanks for your work,
Best
tostrio

**Comment by tssm** [comment]
I think it's because the theme only declares GUI colors so if you are using a true color terminal you can ignore it.

To fix the colors make sure you have `set termguicolors` in your `~/.vimrc`/`~/config/nvim/init.vim`.

**Comment by aereal** [comment]
Sorry for slow response.

Currently this colorscheme does not support CUI environment.

The problem is issue ( #2 ) created by me but I have almost no motivation because it is difficult to reproduce same experience as GUI on CUI.
